spring.application.name=EmotionBased_Recommandation



# ===== Server =====
server.port=8081


# ===== MySQL Database =====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DRIVER_CLASS}


# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== File Upload (for face images) =====
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

emotion.api.url=${EMOTION_URL}
emotion.api.secret=${EMOTION_KEY}
emotion.api.key=${EMOTION_API_KEY}


youtube.api.url=${YOUTUBE_URL}
youtube.api.key=${YOUTUBE_API}



spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile





jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

gemini.api.url=${GEMINI_URL}
gemini.api.key=${GEMINI_API_KEY}





# (usually handled in a @Configuration class, but noting the port here for reference)
